config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index'

  resources :users, only: [:show]
  resources :articles do
    collection do
      get :draft_index
    end
    resources :comments, only: :create
    resource :favorites, only: [:show, :create, :destroy]
  end
  post 'articles/:tag', to: 'articles#create'
  get '/search', to:'search#index'
  get '/search/:word', to: 'search#index'
  get '/users/:id/:favorite', to: 'user#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  enum status: { draft: 0, publishd: 1 }

  acts_as_taggable_on :labels
  acts_as_taggable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord
    belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments
  has_many :favorites
  
  mount_uploader :icon, IconUploader

  scope :writen_article, -> (user_id) { find(user_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :icon])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @articles = Article.publishd
    user = User.all

    @articles_and_users = []
    @articles.each do |article|
      post = {}
      post[:article] = article
      post[:user] = User.writen_article(article.user_id)
      @articles_and_users << post
    end
  end

  def draft_index
    @drafts = current_user.articles.draft
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
    @chk_favorite = Favorite.find_by(user_id: current_user.id, article_id: @article.id) if user_signed_in?
  end

  def new
    @article = Article.new
  end

  def create
    if params[:commit] == '公開'
      current_user.articles.create(article_params.merge(status: 1))
    else
      current_user.articles.create(article_params.merge(status: 1))
    end

    redirect_to :root
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    article.update(article_params)

    redirect_to action: :index
  end

  def destroy
    Article.find(params[:id]).delete

    redirect_to action: :index
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    current_user.comments.create(comment_params)

    redirect_to article_path(params[:article_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :article_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
    article_id = params[:article_id]
    article_id.to_f
    @favorite =  Favorite.find_by(user_id: current_user.id, article_id: article_id)
  end
  def create
    current_user.favorites.create(incompetence: true, article_id: params[:article_id])
    redirect_to article_path(params[:article_id])
  end

  def destroy
    Favorite.find_by(user_id: current_user.id, article_id: params[:article_id]).destroy
    redirect_to article_path(params[:article_id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    word = params[:word]
    if word != ''
      @articles = Article.where("title LIKE ?", "%#{params[:word]}%")
    else
      @articles = Article.publishd
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

    @articles = @user.articles.page(params[:page]).per(4).order('created_at DESC')
    if params[:favorite] == ''
      @user_articles = Article.find(@user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.erb
<div class='article'>
  <%= link_to article_path(article) do %>
    <h2><%= article.title %></h2>
  <% end %>

  <%= link_to user_path(article.user_id) do %>
    <h5 class='article__author'>作成者 : </h5>
    <p class='article__author__name'><%= article.user.name %></p>
  <% end %>

  <% article.tag_list.each do |tag| %>
    <span><%= tag %></span>
  <% end %>

  <%= link_to '編集', edit_article_path(article) if current_user.id == article.user_id %>
  <%= link_to '削除', article_path(article), method: :DELETE %>
</div>

app/views/articles/_article.haml
%h2
  作成者
  = article.user.name
  = article.title
= article.content
= link_to '詳細', article_path(article)
= link_to '編集', edit_article_path(article)
= link_to '削除', article_path(article), method: :DELETE

= link_to '新規投稿', new_article_path

app/views/articles/_article0.haml
%h2
  作成者
  = article.user.name
  = article.title
= article.content
= link_to '詳細', article_path(article)
= link_to '編集', edit_article_path(article)
= link_to '削除', article_path(article), method: :DELETE

= link_to '新規投稿', new_article_path

app/views/articles/draft_index.haml
- @drafts.each do |article|
  %h2
    作成者
  .username
    = article.user.name
  %h5.title
    Title
  = article.title
  %h5.content
    = article.content

  .menu
    = link_to '詳細', article_path(article)
    = link_to '編集', edit_article_path(article)
    = link_to '削除', article_path(article), method: :DELETE

= link_to '新規投稿', new_article_path
= link_to '下書き一覧', draft_index_articles_path

app/views/articles/edit.html.erb
<h2>Edit</h2>
<%= react_component('ArticleEdit', article: @article) %>

app/views/articles/index.html.erb
<h2>新着記事</h2>
<%= react_component('ArticleBox', url:"articles", articles_and_users: @articles_and_users ,tags: @tags) %>


<!-- <%= link_to '公開一覧', articles_path %>
<%= link_to '下書き一覧', draft_index_articles_path if user_signed_in? %> -->

app/views/articles/new.haml
= form_for @article do |f|
  = f.text_field :title, class: 'row form-control', id: 'aaa'
  = f.text_field :tag_list, class: 'row form-control'
  .row
    .col-md-6
      = f.text_area :content, id: 'edit-content', class: 'form-control', size: '50x25'
    .col-md-6
      #preview

  = f.submit '送信', class: 'row btn btn-primary'

app/views/articles/show.html.erb
<%= react_component('ArticleShow', article: @article, current_user: current_user, favorite: @chk_favorite, user: @user) %>

app/views/layouts/_header.erb
<div class='header'>
  <%= link_to 'ShowTa', root_path, :class => "app-title" %>
  <%= react_component('SearchForm') %>
  <ul class='header__list'>
    <% if user_signed_in? %>
      <li class='header__list__content'>
        <span class='dropdown'>
          <a class='dropdown-toggle' data-toggle='dropdown'>
            <%= image_tag current_user.icon, class: 'header__list__content__user-icon' %>
          </a>
          <ul class='dropdown-menu header__list__content__dropdown'>
            <li>
              <%= link_to 'My Page', user_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </span>
      </li>
      <li class='header__list__content'>
        <span>
          <a href="/articles/new" class="btn btn-default header__list__content__new-post">
            <%= fa_icon "external-link" %>
            新規投稿
          </a>
        </span>
        <span class='dropdown header__lsit__content__dropdown'>
          <a class='btn btn-default dropdown-toggle header__list__content__dropdown__link' data-toggle='dropdown'>
            <%= fa_icon 'sort-desc', class: 'header__list__content__dropdown__link--icon' %>
          </a>
          <ul class='dropdown-menu header__list__content__dropdown'>
            <li>
              <%= link_to '下書き', draft_index_articles_path %>
            </li>
          </ul>
        </span>
      </li>
    <% else %>
      <li class='header__list__content'>
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>
      <li class='header__list__content'>
        <%= link_to 'Sign in', new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowTa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShowTa
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/header"
    = yield

app/views/search/index.html.erb
<div class="searchform">
  <%= react_component('SearchForm') %>
</div>
<%= react_component('SearchList', articles: @articles) %>

app/views/users/show.erb
<div class='contents row'>
  <h2>
    <%= "#{@user.name}さんの投稿一覧" %>
  </h2>

  <% @articles.each do |article| %>
    <%= render partial: 'articles/article', locals: { article: article } %>
  <% end %>

  <%= paginate(@articles) %>
</div>

<%= react_component('MyPage', user: @user, articles: @user_articles) %>

app/views/users/show.haml
.contents.row
  %p
    = @nameさんの投稿一覧
  - @articles.each do |article|
    = render partial: "articles/article", locals: { article: article }
  = paginate(@articles)